AWSTemplateFormatVersion: 2010-09-09
Description: Database
Parameters:
  aVPC:
      Description: VPC to deploy resources
      Type: AWS::EC2::VPC::Id
  AMItoUse:
      Description: AMI used for base image
      Type: String
  KeyName:
      Description: EC2 KeyPair name for SSH access
      Type: 'AWS::EC2::KeyPair::KeyName'
      ConstraintDescription: Is name of existant EC2 KeyPair.
  PublicSubnet:
      Description: Web Server subnet
      Type: AWS::EC2::Subnet::Id
Resources:
  aWebAccessSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow host http
        VpcId:
          Ref: aVPC
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/32
	  - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/16
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/24
        
  aWebServerInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: !Ref AMItoUse
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "aWebAccessSecurityGroup"
          SubnetId: 
            Ref: "PrivateSubnet"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          service httpd start
Outputs:
  aWebServerInstanceID:
    Description: InstanceId of EC2 instance
    Value: !Ref aWebServerInstance